backend:
  image:
    repository: isadiac/orders-backend
    tag: "1.0"
  replicaCount: 1
  service:
    port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  image:
    repository: gabrielabejarano09/pedidos-frontend
    tag: "1.0"
  replicaCount: 1
  service:
    port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

db:
  auth:
    username: pedido_user
    database: pedidos
  primary:
    persistence:
      enabled: true

ingress:
  enabled: true