apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gabrielabejarano09/pedido-app-repo
    targetRevision: main
    path: charts/pedidos-app
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
        - values-secret.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pedidos-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
