apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
            - name: DB_HOST
              value: "{{ .Release.Name }}-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "{{ .Values.db.auth.database }}"
            - name: DB_USER
              value: "{{ .Values.db.auth.username }}"
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password
            - name: DB_HOST
              value: "{{ .Release.Name }}-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "{{ .Values.db.auth.database }}"
            - name: DB_USER
              value: "{{ .Values.db.auth.username }}"
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"